language: objective-c
osx_image: xcode11.5

xcode_project: PassiveDataKit.xcodeproj 
xcode_scheme: PassiveDataKit

before_install:
- brew update
- brew tap oclint/formulae
- brew install oclint

script:
- set -o pipefail
- xcodebuild test -scheme "PassiveDataKit" -workspace "PassiveDataKit.xcworkspace" -destination "platform=iOS Simulator,name=iPhone 8,OS=13.5" ARCHS="x86_64" VALID_ARCHS="x86_64" ONLY_ACTIVE_ARCH="YES" | xcpretty
- xcodebuild -workspace "PassiveDataKit.xcworkspace" -scheme "PassiveDataKit" -destination "platform=iOS Simulator,name=iPhone 8,OS=13.5" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" COMPILER_INDEX_STORE_ENABLE="NO" ARCHS="x86_64" VALID_ARCHS="x86_64" ONLY_ACTIVE_ARCH="NO" | xcpretty -r json-compilation-database --output compile_commands.json
- oclint-json-compilation-database -v
  -e AFNetworking
  -e DTMHeatmap
  -e AppAuth
  --
  -disable-rule=PreferEarlyExit
  -disable-rule=LongMethod
  -disable-rule=LongVariableName
  -disable-rule=HighCyclomaticComplexity 
  -disable-rule=HighNPathComplexity
  -disable-rule=HighNcssMethod

