language: objective-c
osx_image: xcode7.3

xcode_project: PassiveDataKit.xcodeproj 
xcode_scheme: PassiveDataKit
xcode_sdk: iphonesimulator9.3

script:
 - xctool -scheme PassiveDataKit -project PassiveDataKit.xcodeproj -sdk iphonesimulator9.3 ARCHS=i386 VALID_ARCHS=i386  CURRENT_ARCH=i386 ONLY_ACTIVE_ARCH=NO -reporter json-compilation-database:compile_commands.json build 
 - xcodebuild test -scheme PassiveDataKitTests -project PassiveDataKit.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
 - oclint-json-compilation-database -e AFNetworking
