language: objective-c
osx_image: xcode9.3

xcode_project: PassiveDataKit.xcodeproj 
xcode_scheme: PassiveDataKit
xcode_sdk: iphonesimulator9.3

before_install:
 - brew cask uninstall oclint
 - brew tap oclint/formulae
 - brew install oclint

script:
 - xcodebuild test -scheme 'PassiveDataKit' -project 'PassiveDataKit.xcodeproj' -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ARCHS='x86_64 arm64 arm7s arm7' VALID_ARCHS='x86_64 arm64 arm7s arm7' ONLY_ACTIVE_ARCH=NO  | xcpretty
 - xcodebuild -project 'PassiveDataKit.xcodeproj' -scheme 'PassiveDataKit' ARCHS='x86_64 arm64 arm7s arm7' VALID_ARCHS='x86_64 arm64 arm7s arm7' ONLY_ACTIVE_ARCH=NO | tee xcodebuild.log  | xcpretty
 - oclint-xcodebuild
 - oclint-json-compilation-database
  -e AFNetworking
  -e DTMHeatmap
  --
  -disable-rule=PreferEarlyExit
  -disable-rule=LongMethod
  -disable-rule=LongVariableName
  -disable-rule=HighCyclomaticComplexity 
  -disable-rule=HighNPathComplexity
  -disable-rule=HighNcssMethod

