language: objective-c
osx_image: xcode9.4

xcode_project: PassiveDataKit.xcodeproj 
xcode_scheme: PassiveDataKit
xcode_sdk: iphonesimulator9.3

before_install:
 - brew cask uninstall oclint
 - brew tap oclint/formulae
 - brew install oclint

script:
# - xcodebuild test -scheme "PassiveDataKit" -project "PassiveDataKit.xcodeproj" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' ARCHS='x86_64' VALID_ARCHS='x86_64' ONLY_ACTIVE_ARCH=NO | xcpretty
# - xcodebuild clean
# - xcodebuild -project "PassiveDataKit.xcodeproj" -scheme "PassiveDataKit" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" COMPILER_INDEX_STORE_ENABLE="NO" ARCHS='x86_64' VALID_ARCHS='x86_64' ONLY_ACTIVE_ARCH=NO | tee xcodebuild.log | xcpretty -r json-compilation-database --output compile_commands.json
 - xcodebuild -project "PassiveDataKit.xcodeproj" -scheme "PassiveDataKit" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" COMPILER_INDEX_STORE_ENABLE="NO" ARCHS='x86_64' VALID_ARCHS='x86_64' ONLY_ACTIVE_ARCH=NO | tee xcodebuild.log
 - oclint-xcodebuild
 - oclint-json-compilation-database
 -e AFNetworking
 -e DTMHeatmap
 --
 -disable-rule=PreferEarlyExit
 -disable-rule=LongMethod
 -disable-rule=LongVariableName
 -disable-rule=HighCyclomaticComplexity 
 -disable-rule=HighNPathComplexity
 -disable-rule=HighNcssMethod

