version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
      TERM: dumb
    steps:
      - checkout
      - run: bundle install
      - run: brew install oclint
      - run: pod install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan


  adhoc:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
      TERM: dumb
    steps:
      - checkout
      - run: bundle install
      - run: brew install oclint
      - run: pod install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
          requires:
            - build-and-test