version: 2.1

jobs:
  build:
    macos:
      xcode: 14.0.0

    steps:
      - checkout
      - restore_cache:
          key: Podfile-{{ checksum "Podfile" }}-{{ checksum "Podfile.lock" }}
      - run:
          name: Update and install Cocoapods and OCLint
          command: |
            sudo gem install cocoapods --quiet
            pod install --silent
      - run:
          name: Build
          command: |
            xcodebuild -workspace "PassiveDataKit.xcworkspace" -scheme "PassiveDataKit" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.0,name=iPhone 14" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" COMPILER_INDEX_STORE_ENABLE="NO" ARCHS="x86_64" VALID_ARCHS="x86_64" ONLY_ACTIVE_ARCH=NO | tee xcodebuild.log | xcpretty -r json-compilation-database --output compile_commands.json
      - run:
          name: Test
          command: |
            xcodebuild test -scheme "PassiveDataKit" -workspace "PassiveDataKit.xcworkspace" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.0,name=iPhone 14" ARCHS="x86_64" VALID_ARCHS="x86_64" ONLY_ACTIVE_ARCH=NO | xcpretty
      - save_cache:
          key: Podfile-{{ checksum "Podfile" }}-{{ checksum "Podfile.lock" }}
          paths:
            - "Pods"
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output
